### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
I think [list-groups](http://getbootstrap.com/components/#list-group) match the style of the site very good.
As for the last commit, you can see if you want to keep it or not.

**Comment by timowest** [comment]
The changes look ok. Do you want to add badges also for yourself and John? Developer or something?

**Comment by Shredder121** [comment]
Yes, that is good.

**Comment by Shredder121** [comment]
@johnktims Do you think `Developer` is good? We can also copy GitHub's naming of `Collaborator`?

**Comment by johnktims** [comment]
@Shredder121  Either one sounds good to me.

**Comment by johnktims** [comment]
I'd probably use `Developer` since that's how you're listed in the pom.xml.

**Comment by Shredder121** [comment]
[For reference, the new page](https://rawgit.com/querydsl/querydsl.com/157c8448622d116585cceecc1f27683789bf48bf/team.html).

**Comment by Shredder121** [comment]
Just wanted to say I have one more idea.

**Comment by Shredder121** [comment]
[For reference, the new page](https://rawgit.com/querydsl/querydsl.com/899e05bec3425e56aa26e7202319c362858ccb76/team.html).

**Comment by Shredder121** [comment]
It does give a little more content, so it doesn't fit on one page without scrolling for me, but it isn't as empty anymore and gives a bit more meaning to the names.
What do you think?

**Comment by timowest** [comment]
It's nice, but maybe John could pick a real photo or a better avatar? The generic github pics are a little weird.

**Comment by Shredder121** [comment]
What is even weirder is the way GitHub handles them.
I'll change the picture to the recommended way of including GitHub content, and I'll show you.

**Comment by Shredder121** [comment]
Hmm, the online version [is okay](https://rawgit.com/querydsl/querydsl.com/6e9f2dca4aa93d220db55e8127452f00a653a396/team.html), but locally it includes 420x420.

**Comment by Shredder121** [comment]
Anyway, the page is then updated whenever we update our avatars (and GitHub's caches are refreshed).
But it works nice.

**Comment by Shredder121** [comment]
I didn't push it yet, sorry. [behold](https://rawgit.com/querydsl/querydsl.com/b8812200b8a50ad096df5ae0881d993b60ab716f/team.html).
GitHub for some reason doesn't scale the resulting image if it is an avatar.

**Comment by johnktims** [comment]
I added a "real" picture. ;)

**Comment by timowest** [comment]
To me this looks ok now. But before using the team URL, I will try to add some internal redirects from releases to releases.html and team to team.html.

**Comment by Shredder121** [comment]
Yes, to me it also looks good.
I think we made it as good as it can be.

**Pull request merged**
