### PR TITLE
A suggested article (if it makes sense)

### PR DESCRIPTION
**Pull request by eugenp**
I published [a few writeups](http://www.baeldung.com/tag/querydsl/) making good use of Querydsl over the last year - I figured I'd contribute one of the links over on the page - if it makes sense of course. 
Perfectly fine if it doesn't. 
Cheers, 
Eugen.

### CODE REVIEW

**Comment by Shredder121** [comment]
Thanks for writing up on that.
However, is it intended when I visit the page for a full page ad to show up?
I mean, I don't know whether many people will keep on reading then.

@querydsl/developers remind me to add a year of publication to the other blog titles, or something like that.

**Comment by Shredder121** [comment]
For reference: [a preview](https://rawgit.com/querydsl/querydsl.com/56da2d4cae90bfdbec5206942d9334a8f3288ae5/index.html).

**Comment by eugenp** [comment]
I never run ads on the site, no - that was probably the optin lightbox for the eBook (I'm guessing). 
Cheers, 
Eugen.

**Comment by johnktims** [comment]
Hey @eugenp. I just found this PR and will get this merged and deployed.

Better late than never. 😅
Thanks for the contribution!

**Pull request merged**
