### PR TITLE
Fix tag

### PR DESCRIPTION
**Pull request by johnktims**

### CODE REVIEW

**Comment by Shredder121** [comment]
There are a few other mismatched tags, I can also update them if you haven't done already.

**Comment by johnktims** [comment]
Hmm... looks like we exclude the entire `.idea` folder in querydsl (https://github.com/querydsl/querydsl/blob/master/.gitignore#L10). I really don't like checking in files for an IDE.

**Comment by johnktims** [comment]
@Shredder121 did I miss any?

I'd really like to reformat these html files. Should I do it here?

**Comment by timowest** [comment]
I am also for excluding all IDE related content

**Comment by Shredder121** [comment]
Okay then. Then it's okay.
I won't commit any IDE related content anyway.

As for reformatting, it's not really necessary, so I abstain. @timowest what do you think?

**Comment by timowest** [comment]
Reformatting preferably via a separate PR.

**Pull request merged**
